from __future__ import annotations
import json
from pathlib import Path
from typing import Any
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from src.pipeline.config import DASHBOARD_JSON_FILENAME

# Load data once at startup
DATA_FILE = Path(DASHBOARD_JSON_FILENAME)

def _load() -> dict:
    if not DATA_FILE.exists():
        return {}
    with DATA_FILE.open(encoding="utf-8") as f:
        return json.load(f)

DATA: dict[str, Any] = _load()

app = FastAPI(
    title="SalesIQ — E-Commerce Sales Intelligence API",
    description=(
        "REST endpoints that expose the cleaned ETL data, product summaries, "
        "regional stats, fraud orders, inventory priority, and AI insights "
        "generated by `solution.py`."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def _require(key: str) -> Any:
    """Return DATA[key] or raise 404 if data not loaded."""
    if not DATA:
        raise HTTPException(
            status_code=503,
            detail="dashboard_data.json not found — run run_pipeline.py first.",
        )
    if key not in DATA:
        raise HTTPException(status_code=404, detail=f"Key '{key}' not in data.")
    return DATA[key]


# -- Health --
@app.get("/", tags=["Health"])
def root():
    """Ping endpoint — verifies the server is reachable."""
    return {
        "status": "ok",
        "message": "SalesIQ API is running. Visit /docs for Swagger UI.",
        "data_loaded": bool(DATA),
    }


@app.get("/health", tags=["Health"])
def health():
    """Returns server health and whether dashboard data is loaded."""
    return {
        "healthy": True,
        "data_file": str(DATA_FILE),
        "data_loaded": bool(DATA),
        "total_orders": DATA.get("meta", {}).get("total_orders", 0),
    }


# -- Meta --
@app.get("/meta", tags=["Overview"])
def get_meta():
    """High-level summary: total orders, revenue, fraud count, products & regions."""
    return _require("meta")


# -- Products --
@app.get("/products", tags=["Products"])
def get_products():
    """Per-product revenue, order count, fraud count, and average unit price."""
    return _require("product_summary")


# -- Regions --
@app.get("/regions", tags=["Regions"])
def get_regions():
    """Per-region total revenue, order count, and fraud count."""
    return _require("region_summary")


# -- Revenue --
@app.get("/revenue/monthly", tags=["Revenue"])
def get_monthly_revenue():
    """Monthly revenue grouped by product."""
    return _require("monthly_revenue")


@app.get("/revenue/daily", tags=["Revenue"])
def get_daily_revenue():
    """Daily revenue grouped by product (Jan 1–25)."""
    return _require("daily_revenue")


# -- Orders --
@app.get("/orders", tags=["Orders"])
def get_orders(limit: int = 50, offset: int = 0):
    """
    Paginated list of all cleaned orders.
    """
    orders = _require("orders")
    return {
        "total": len(orders),
        "offset": offset,
        "limit": limit,
        "orders": orders[offset : offset + limit],
    }


# -- Fraud --
@app.get("/fraud", tags=["Fraud"])
def get_fraud_orders():
    """All flagged fraud orders with order ID, product, region, revenue, and date."""
    return _require("fraud_orders")


# -- Inventory --
@app.get("/inventory", tags=["Inventory"])
def get_inventory_priority():
    """Min-heap inventory restock priority list (lowest score = restock first)."""
    return _require("inventory_priority")


# -- Heatmap --
@app.get("/heatmap", tags=["Analytics"])
def get_heatmap():
    """Average revenue heatmap: product × hour-bin (0-8, 9-16, 17-23)."""
    return _require("heatmap")


# -- AI Insights --
@app.get("/insights", tags=["AI Insights"])
def get_insights():
    """Rule-based AI business insights generated from the cleaned ETL data."""
    return _require("ai_insights")
